### ISSUE TITLE
Using the decorator without parentheses throws

### ISSUE THREAD

**Issue by bertdeblock** [jelhan/ember-local-storage-decorator#11]
Both when reading from / writing to the decorated property.

Example write error:
> Cannot assign to read only property 'foo' of object '[object Object]'

**Comment by jelhan** [comment]
Thanks a lot for reporting.

```js
// this works
@localStorage()
foo;

// this is not supported yet
@localStorage
foo;
```

More technically speaking the available export provides a generator function. It returns itself a function based on the arguments. The returned function decorates the property. Conceptually it looks like this:

```js 
export default function() {
  return function(target, key, descriptor) {
    // do something with the class property
  }
}

```

Supporting `@localStorage` without being called (parentheses) would require to export a function, which itself directly decorates the value.

```js
export default function(target, key, descriptor) {
  // decorate class property
}
```

To be honest I don't know how the same export could support both. I know it's possible. Ember Data's `@attr` decorator could be used in both forms: `@attr` and `@attr('string')`. But I haven't had time yet to figure out how that magic works.

Would appreciate a hint or even better a PR if someone is motivated to teach me. :smile_cat:

**Comment by Windvis** [comment]
@jelhan I gave this a try a week ago to learn more about decorators. I have a WIP branch that I can finish up this weekend if you want :smile:.
