### ISSUE TITLE
autotracking between tabs

### ISSUE THREAD

**Issue by lifeart** [jelhan/ember-local-storage-decorator#4]
it will be great to have flag, to allow tracking local storage mutations by key across tabs

usecase: shopping cart

**Comment by lifeart** [comment]
woops, it's already mentioned in readme, sorry, closing ticket

**Comment by jelhan** [comment]
Wouldn't make much sense without. :wink: But to be honest I haven't tested yet if it's actually working. So if you find bugs please let me know.
