### ISSUE TITLE
"Using and updating a value during the same computation" error

### ISSUE THREAD

**Issue by bertdeblock** [jelhan/ember-local-storage-decorator#8]
Hi 👋! Thank you for making this!

When using the decorator, I'm running into the same error described here: https://github.com/pzuraq/tracked-maps-and-sets/issues/14. It also proposes a possible solution.

**Comment by jelhan** [comment]
What is your use case? The use case discussion in https://github.com/pzuraq/tracked-maps-and-sets/issues/14 seems seems to be default value. `@localStorage` decorator supports default values out of the box.

**Comment by bertdeblock** [comment]
I was just testing this out locally and using the decorator in a component which is rendered multiple times on the same page triggers the error.

Edit: Rendering the component only once seems to trigger the error as well.
